### ISSUE TITLE
adding "power" support

### ISSUE THREAD

**Issue by ghatwala** [templexxx/reedsolomon#16]
Hi @templexxx ,

Have you tried adding power architecture (ppc64le) support and creating those relevant go/assembly files

"galois_ppc64le.go/galois_ppc64le.s" similar to what is done here - "https://github.com/klauspost/reedsolomon" ?

**Comment by templexxx** [comment]
@ghatwala 

Hi,

I'm sorry, I know nothing about ppc64le asm. Maybe I will try it later, but it will take time

**Comment by ghatwala** [comment]
@templexxx  -  just wanted to confirm if below understanding is correct.
The routines that have been optimized for amd64 and are present in " galois_amd64.go" in klauspost repo.
o galMulSlice
o galMulSliceXor
o sliceXor
The un-optimized implementation of the above routines is in "galois_noasm.go " and This would be the one that is getting invoked for Power currently. ?

Let us know if above approach/understanding would be good in optimizing "reedsolomon" for ppc64le ?

**Comment by templexxx** [comment]
@ghatwala 

You're right. On Power, it will call funcutions in "galois_noasm.go".
