### ISSUE TITLE
possible to upstream your improvement?

### ISSUE THREAD

**Issue by rogers0** [templexxx/reedsolomon#9]
Thanks for your work!

I'm package maintainer of klauspost/reedsolomon in Debian:
 - https://tracker.debian.org/pkg/golang-github-klauspost-reedsolomon

I'm wondering:
 - whether you can send you improved patches upstream, to: https://tracker.debian.org/pkg/golang-github-klauspost-reedsolomon?
 - upstream recently supported NEON support for arm64: https://github.com/klauspost/reedsolomon/commit/7b88f42. is it suitable for your fork?

**Comment by templexxx** [comment]
@rogers0 

you can do anything you want

I need some more test about arm64 NEON, I think I will support it next week

klauspost/reedsolomon did really good job on it
